### ISSUE TITLE
Update with license?

### ISSUE THREAD

**Issue by strtw** [hectordiazgomez/azure_openai_react#1]
Thanks for sharing this repo Hector, was wondering if you could license it for open source? 

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

**Comment by hectordiazgomez** [comment]
Sure, the repo is under the MIT license now.

**Comment by strtw** [comment]
Thank you!
